[feat] revisão do css dos componentes
uxshop/storefront-components pull request #15
Opened 2022-11-14 13:16 UTC by vitorbruski

## [feat] revisão do css dos componentes

[feat link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront-2?workitem=3319)

### Changes:

- revisão do css feita de acordo com o projeto no figma

2022-11-14 13:18 UTC, vitorbruski commented
@tiagotermedooca preciso confirmar sobre os tamanhos de fontes com você. eu devo seguir a risca os tamanhos no figma? (eles parecem um pouco grandes, na minha opinião)

2022-11-17 13:45 UTC, simaomeyrerdooca commented
O CSS  está sendo desenvolvido em mobile first?

2022-11-21 12:09 UTC, simaomeyrerdooca requested changes

2022-11-21 12:09 UTC, simaomeyrerdooca commented on src/components/ux-carousel-item/ux-carousel-item.scss
> +@media (min-width: $tablet-large) {
O CSS está sendo desenvolvido em mobile first?

2022-11-21 12:12 UTC, vitorbruski commented on src/components/ux-carousel-item/ux-carousel-item.scss
> +@media (min-width: $tablet-large) {
sim, alguma coisa nao esta de acordo?

2022-11-21 12:19 UTC, simaomeyrerdooca commented on src/components/ux-carousel-item/ux-carousel-item.scss
> +@media (min-width: $tablet-large) {
Só pra confirmar se já estava assim mesmo

2022-11-21 12:19 UTC, simaomeyrerdooca approved these changes

2022-11-22 13:29 UTC, felipesantosdooca approved these changes

2022-11-25 13:55 UTC, merged