fix] Componente Carrossel e Carrossel Item
uxshop/storefront-components pull request #24
Opened 2022-12-27 13:00 UTC by vitorbruski

## [fix] Componente Carrossel e Carrossel Item

[fix link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront-5?workitem=5197)

### Changes:

- corrigido wrapper de carousel e carousel item para o landing-editor

2022-12-27 13:11 UTC, tiagotermedooca requested changes

2022-12-27 13:11 UTC, tiagotermedooca commented on src/components/ux-carousel-item/ux-carousel-item-type.ts
> +  dataTitle?: string;
faltou configurar o prettier, pois está colocando `;` onde não precisa

2022-12-27 13:11 UTC, tiagotermedooca commented on src/components/ux-carousel-item/ux-carousel-item.tsx
> +  @Prop() dataTitle?: string;
faltou configurar o prettier, pois está colocando ; onde não precisa

2022-12-27 13:11 UTC, tiagotermedooca commented on src/components/ux-carousel/ux-carousel.tsx
> +  @Prop() dataRewind: boolean;
faltou configurar o prettier, pois está colocando ; onde não precisa

2022-12-27 13:19 UTC, vitorbruski commented on src/components/ux-carousel-item/ux-carousel-item.tsx
> +  @Prop() dataTitle?: string;
onde posso encontrar a configuração ideal do prettier?

2022-12-27 19:05 UTC, diovaniBelleboni approved these changes

2022-12-28 12:08 UTC, tiagotermedooca approved these changes

2022-12-28 18:00 UTC, merged