Feat/ux banners
uxshop/storefront-components pull request #3
Opened 2022-07-29 14:28 UTC by ofelipesant

## [Task] Component UX-Banners
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/Storefront%20Team/Platform/Storefront%205?workitem=1660)
### Changes:
- criação da estrutura do componente
- estilização e responsividade
- composição de testes unitários e e2e

2022-07-29 17:12 UTC, tiagotermedooca requested changes

2022-07-29 17:12 UTC, tiagotermedooca commented on src/components/ux-banners/ux-banners.tsx
> +              <img class="img" src={image?.srcMobile || image?.srcDesktop} alt={image?.alt} />
faltou a mobile, a tag img é um fallback, então melhor deixar somente a desktop

2022-07-29 17:39 UTC, ofelipesant commented on src/components/ux-banners/ux-banners.tsx
> +              <img class="img" src={image?.srcMobile || image?.srcDesktop} alt={image?.alt} />
@tiagotermedooca ajustado. Ajustei também o breakpoint pois estava distorcendo a imagem. vou adicionar os breakpoints e mixins globais conforme tu tinha dito na próxima PR

2022-07-30 11:23 UTC, tiagotermedooca approved these changes

2022-07-30 11:23 UTC, merged