[task]: Refatora componente ux-testimonials
uxshop/storefront-components pull request #32
Opened 2023-01-10 19:15 UTC by Lima08

[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront-6?workitem=5511)

Changes:
- [ ] Ajusta reatividade
- [ ] Adiciona campo Email
- [ ] Remove componentes sem mensagem

2023-01-10 20:40 UTC, kevenssousa approved these changes

2023-01-10 20:48 UTC, simaomeyrerdooca requested changes

2023-01-10 20:48 UTC, simaomeyrerdooca commented on src/components/ux-testimonials/ux-testimonials.tsx
> +            this.testimonials.map(testimonial => (
por não ter o atributo de `key` não chega a logar erro no console?

2023-01-11 12:19 UTC, simaomeyrerdooca approved these changes

2023-01-11 12:25 UTC, kevenssousa approved these changes

2023-01-11 12:26 UTC, merged