[task] Revisão de componente text image
uxshop/storefront-components pull request #34
Opened 2023-01-13 18:07 UTC by Lima08

[Link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront-6?workitem=5514)

Changes:

Atualiza propriedades do componente, schema e css

2023-01-13 18:15 UTC, simaomeyrerdooca requested changes

2023-01-13 18:15 UTC, simaomeyrerdooca commented on src/components/ux-text-image/ux-text-image.tsx
> +  @Prop() dataButtonLabel: string
As props opcionais por padrão sempre mantemos por último

2023-01-13 19:20 UTC, simaomeyrerdooca approved these changes

2023-01-16 14:11 UTC, diovaniBelleboni approved these changes

2023-01-16 19:59 UTC, merged