[Task] Correção bugs Vitrine
uxshop/storefront-components pull request #36
Opened 2023-01-25 14:55 UTC by Lima08

Correção bugs Vitrine
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront-7?workitem=5754)

Changes:
- Refatora css passando para abordagem mobile first
- Adiciona css global nas configurações
- Corrige renderização máxima de cards da vitrine em visão mobile

2023-01-26 17:38 UTC, simaomeyrerdooca requested changes

2023-01-26 17:38 UTC, simaomeyrerdooca commented on src/components/ux-showcase-item/ux-showcase-item.tsx
> +                  <span class="price"> &nbsp; {currencyFormatter(this.dataPrice)}</span>
remover `&nbsp;`

2023-01-26 19:11 UTC, Lima08 commented on src/components/ux-showcase-item/ux-showcase-item.tsx
> +                  <span class="price"> &nbsp; {currencyFormatter(this.dataPrice)}</span>
Precisamos dele para dar um espaço entre os spans. Algum motivo para remover?

2023-01-26 19:33 UTC, simaomeyrerdooca requested changes

2023-01-26 19:33 UTC, simaomeyrerdooca commented on src/components/ux-showcase-item/ux-showcase-item.tsx
> +                  <span class="price"> &nbsp; {currencyFormatter(this.dataPrice)}</span>
não fica melhor se estilizar a classe `prices` pra dar o espaçamento?

2023-01-26 20:12 UTC, Lima08 commented on src/components/ux-showcase-item/ux-showcase-item.tsx
> +                  <span class="price"> &nbsp; {currencyFormatter(this.dataPrice)}</span>
Boa!

2023-01-27 13:55 UTC, simaomeyrerdooca approved these changes

2023-01-27 15:32 UTC, kevenssousa approved these changes

2023-01-27 16:01 UTC, merged